backend:
  name: github
  repo: frillsdev/frills.dev
  branch: main
  auth_scope: repo
commit_messages:
    create: ğŸ“ Add {{collection}} - {{slug}}
    update: ğŸ“ Update {{collection}} - {{slug}}
    delete: ğŸ”¥ Delete {{collection}} - {{slug}}
    uploadMedia: ğŸ–¼ï¸ Upload {{path}}
    deleteMedia: ğŸ”¥ Delete â€œ{{path}}â€
    openAuthoring: '{{message}}'

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"


collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    slug: "{{slug}}"
    path: "{{year}}/{{month}}/{{slug}}"
    format: "frontmatter"
    extension: "md"
    create: true
    # preview_path: "/blog/{{year}}/{{month}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Include in RSS", name: "rss", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
