backend:
  name: github
  repo: frillsdev/frills.dev
  branch: main
  auth_scope: repo
  site_domain: https://frills-dev.pages.dev
  base_url: https://frills-dev.pages.dev
  auth_endpoint: /api/auth
  commit_messages:
    create: ğŸ“ Add {{collection}} - {{slug}}
    update: ğŸ“ Update {{collection}} - {{slug}}
    delete: ğŸ”¥ Delete {{collection}} - {{slug}}
    uploadMedia: ğŸ–¼ï¸ Upload {{path}}
    deleteMedia: ğŸ”¥ Delete â€œ{{path}}â€
    openAuthoring: "{{message}}"

logo_url: /images/logo-cms.gif

media_folder: "public/images/uploads"
public_folder: "/public/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publication Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Include in RSS", name: "rss", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "bookmarks"
    label: "Bookmarks"
    folder: "src/content/bookmarks"
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Publication Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", default: "" }
      - { label: "Include in RSS", name: "rss", widget: "boolean", default: true }
